version: '3'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: haystack-image
    environment:
      - "discovery.type=single-node"
    volumes:
      - esdata1:/usr/share/elasticsearch/data:rw
    ports:
      - 9200:9200
    networks:
      - default
    restart: unless-stopped
volumes:
  esdata1:
    driver: local